// Operators in java 
// types 
// Arithematic =  + - * / % =
// relational  =  <> <= >=
// logical     =  == ! != && || 
// bitwise     
 
//  wap to accept two numbers from the user and calculate their sum and print on output

// step1 create java file
// Step2 import scanner 
// step3 declare class 
// step4 write java main method
// step5 declare and initilize scanner object
// step6 inform user to enter integer
// step7 declare number 1 and initilize it by calling scanner class nextint()
// same for number 2
// step8 declare an integer variable name result and initilize it by calculating  sum
// step9 
